version: "2"
services:
  app:
    build: .
    container_name: "graphql_app"
    volumes:
      - ./:/app
    ports:
       - "3000:3000"
    links:
       - mongo
  mongo:
    image: mongo:latest
    container_name: "graphql_mongodb"
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    logging:
        driver: "none"
  mongodata:
      image: tianon/true
      volumes:
          - /data/db
